import math
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.tri as tri

# Import your custom classes and functions
from Geometry import NozzleWall
from Thermo_Gas_Calculations import GasDynamics
from MoC_Functions import Node, calculate_interior_point, calculate_centerline_point, calculate_wall_point

# --- 1. INITIALIZATION ---
print("Initializing engines and geometry...")
aero = GasDynamics(gamma=1.4)

# Define the divergent nozzle wall (Bezier Control Points)
# A true contoured bell nozzle for 1D validation
P0 = (0.0, 1.0)
P1 = (2.0, 2.0)
P2 = (4.0, 2.5)
P3 = (5.0, 2.5) # Wall flattens out here!
wall = NozzleWall(P0, P1, P2, P3)

# --- 2. THE INITIAL VALUE LINE (IVL) - RADIAL SOURCE FLOW ---
print("Setting up Radial Source Flow Initial Value Line...")
num_points = 50
initial_M = 1.05
initial_nu = aero.get_nu(initial_M)
initial_mu = aero.get_mu(initial_M)

current_line = []
throat_x = 0.005

# A. Find the wall point and its local slope (theta_max)
t_start = wall.get_t_from_x(throat_x)
x_wall, y_wall = wall.get_point(t_start)

# Use finite difference to approximate the wall angle at the starting x
dt = 0.0001
x_next, y_next = wall.get_point(min(t_start + dt, 1.0))
theta_max = math.atan2(y_next - y_wall, x_next - x_wall)

# B. Calculate the virtual source geometry
R_source = y_wall / math.sin(theta_max)
x_source = x_wall - R_source * math.cos(theta_max)

# C. Build the Initial Value Line along the arc
for i in range(num_points):
    theta_i = (i / (num_points - 1)) * theta_max
    x_i = x_source + R_source * math.cos(theta_i)
    y_i = R_source * math.sin(theta_i)
    node = Node(x=x_i, y=y_i, M=initial_M, theta=theta_i, nu=initial_nu, mu=initial_mu)
    current_line.append(node)

# --- 3. THE MARCHING LOOP ---
print("Marching characteristics downstream...")
history = [current_line]
line_count = 0
max_lines = 300

while current_line[0].x < wall.x3 and line_count < max_lines:
    next_line = []

    # A. Calculate Centerline Point
    node_cl = calculate_centerline_point(current_line[1], aero)
    next_line.append(node_cl)

    # B. Calculate Interior Points
    for i in range(1, num_points - 1):
        node_up = current_line[i + 1]
        node_down = next_line[i - 1]
        node_int = calculate_interior_point(node_up, node_down, aero)
        next_line.append(node_int)

    # C. Calculate Wall Point
    node_below = next_line[-1]
    node_wall = calculate_wall_point(node_below, wall, aero)
    next_line.append(node_wall)

    # D. Store data and step forward
    history.append(next_line)
    current_line = next_line
    line_count += 1

print(f"Solver finished! Generated {line_count} characteristics.")

# --- 4. THRUST CALCULATION ---
# Extract the final characteristic line generated by the solver
exit_nodes = history[-1]

# Build arrays for integration
y_vals = np.array([node.y for node in exit_nodes])
m_vals = np.array([node.M for node in exit_nodes])
theta_vals = np.array([node.theta for node in exit_nodes])

# Define chamber conditions
gamma = 1.4
R_gas = 287.05      # J/(kg*K) for air
P0 = 1000000.0      # Chamber Total Pressure in Pascals (1 MPa)
T0 = 3000.0         # Chamber Total Temperature in Kelvin
P_amb = 101325.0    # Ambient Pressure in Pascals (1 atm)

# Thermodynamics and Kinematics
t_vals = T0 / (1.0 + 0.5 * (gamma - 1.0) * m_vals**2)
p_vals = P0 / (1.0 + 0.5 * (gamma - 1.0) * m_vals**2)**(gamma / (gamma - 1.0))
rho_vals = p_vals / (R_gas * t_vals)

v_vals = m_vals * np.sqrt(gamma * R_gas * t_vals)
vx_vals = v_vals * np.cos(theta_vals)

# Integrate Momentum Flux + Net Pressure Force using trapezoidal rule
integrand = rho_vals * vx_vals**2 + (p_vals - P_amb)
half_thrust = np.trapezoid(integrand, y_vals)
total_thrust_2d = 2.0 * half_thrust

print("\n========================================")
print("           NOZZLE PERFORMANCE           ")
print("========================================")
print(f"Chamber Pressure : {P0 / 1e5:.2f} bar")
print(f"2D Planar Thrust : {total_thrust_2d:.2f} N/m (per meter depth)")
print("========================================\n")


# --- 5. VISUALIZATION AND POST-PROCESSING ---
print("Plotting flowfield and characteristic grid...")

x_vals, y_vals_plot, mach_vals = [], [], []
wall_x_moc, wall_m_moc = [], []

for line in history:
    for i, node in enumerate(line):
        if node.x <= wall.x3 + 0.1:
            x_vals.append(node.x)
            y_vals_plot.append(node.y)
            mach_vals.append(node.M)

            if i == len(line) - 1:
                wall_x_moc.append(node.x)
                wall_m_moc.append(node.M)

# The Wall Padding Fix
dense_wall_x, dense_wall_y = [], []
for i in range(200):
    t = i / 199.0
    px, py = wall.get_point(t)
    if px <= wall.x3:
        dense_wall_x.append(px)
        dense_wall_y.append(py)

dense_wall_m = np.interp(dense_wall_x, wall_x_moc, wall_m_moc)

x_vals.extend(dense_wall_x)
y_vals_plot.extend(dense_wall_y)
mach_vals.extend(dense_wall_m)

# Mirror data
x_full = x_vals + x_vals
y_full = y_vals_plot + [-y for y in y_vals_plot]
mach_full = mach_vals + mach_vals

plt.figure(figsize=(14, 7))

levels = 40
contour = plt.tricontourf(x_full, y_full, mach_full, levels=levels, cmap='jet')
plt.colorbar(contour, label='Mach Number')

for j in range(1, len(history)):
    curr = history[j]
    prev = history[j - 1]
    if curr[0].x > wall.x3:
        break

    for i in range(len(curr)):
        if i < len(curr) - 1:
            plt.plot([prev[i + 1].x, curr[i].x], [prev[i + 1].y, curr[i].y], color='black', lw=0.3, alpha=0.5)
            plt.plot([prev[i + 1].x, curr[i].x], [-prev[i + 1].y, -curr[i].y], color='black', lw=0.3, alpha=0.5)
        if i > 0:
            plt.plot([curr[i - 1].x, curr[i].x], [curr[i - 1].y, curr[i].y], color='black', lw=0.3, alpha=0.5)
            plt.plot([curr[i - 1].x, curr[i].x], [-curr[i - 1].y, -curr[i].y], color='black', lw=0.3, alpha=0.5)

wall_x, wall_y_top, wall_y_bottom = [], [], []
for i in range(101):
    t = i / 100.0
    px, py = wall.get_point(t)
    wall_x.append(px)
    wall_y_top.append(py)
    wall_y_bottom.append(-py)

plt.plot(wall_x, wall_y_top, 'k-', linewidth=4)
plt.plot(wall_x, wall_y_bottom, 'k-', linewidth=4)

plt.title(f'Supersonic Nozzle Flow - Method of Characteristics ($M_i$={initial_M:.2f})', fontsize=16)
plt.xlabel('Axial Position (x)', fontsize=12)
plt.ylabel('Radial Position (y)', fontsize=12)
plt.axis('equal')
plt.show()